REATE TABLE SMARTDROFFICE.CLIENT(
  CLIENT_ID BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL,
  EMAIL_ID VARCHAR(255) UNIQUE,
  NAME VARCHAR(255),
  FIRST_NAME VARCHAR(50),
  MIDDLE_NAME VARCHAR(50),
  LAST_NAME VARCHAR(50),
  GENDER VARCHAR(1),
  ADDRESS_1 VARCHAR(30),
  ADDRESS_2 VARCHAR(30),
  CITY VARCHAR(30),
  STATE VARCHAR(30),
  CELL VARCHAR(12),
  HOME_PHONE VARCHAR(12),
  CREATE_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UPDATE_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE SMARTDROFFICE.PATIENT(
  PATIENT_ID BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL,
  CLIENT_ID BIGINT NOT NULL,
  NAME VARCHAR(150),
  FIRST_NAME VARCHAR(50),
  MIDDLE_NAME VARCHAR(50),
  LAST_NAME VARCHAR(50),
  GENDER VARCHAR(1) NOT NULL,
  AGE INT NOT NULL,
  RELATION VARCHAR(20) NOT NULL,
  CREATE_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UPDATE_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (CLIENT_ID) REFERENCES SMARTDROFFICE.CLIENT (CLIENT_ID)
);

CREATE TABLE SMARTDROFFICE.INSURANCE (
  `INS_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `CLIENT_ID` bigint(20) DEFAULT NULL,
  `PATIENT_ID` bigint(20) DEFAULT NULL,
  `MEMBER_ID` varchar(30) NOT NULL,
  `GROUP_ID` varchar(30) NOT NULL,
  `MEMBER_NAME` varchar(50) NOT NULL,
  `PLAN_TYPE` varchar(30) NOT NULL,
  `CP_PCP` decimal(10,2) DEFAULT NULL COMMENT 'Copay Primary Care',
  `CP_SC` decimal(10,2) DEFAULT NULL COMMENT 'Copay Speciality Care',
  `CP_EC` decimal(10,2) DEFAULT NULL COMMENT 'Copay Emergency Care',
  `CP_UC` decimal(10,2) DEFAULT NULL COMMENT 'Copay Urgent Care',
  `PRESCRIPTION_GENERIC` decimal(10,2) DEFAULT NULL COMMENT 'Prescription Copay Generic',
  `PRESCRIPTION_BRAND` decimal(10,2) DEFAULT NULL COMMENT 'Prescription Copay Branded',
  `PLAN_CONTACT` varchar(30) DEFAULT NULL COMMENT 'Plan Contact Number',
  `IN_NW_DEDUCTIBLE` bigint(20) DEFAULT NULL COMMENT 'In-Network Deductible',
  `IN_NW_COINSURANCE` bigint(20) DEFAULT NULL COMMENT 'In-Network Co-Insurance',
  `OUT_NW_DEDUCTIBLE` bigint(20) DEFAULT NULL COMMENT 'Out-Of-Network Deductible',
  `OUT_NW_COINSURANCE` bigint(20) DEFAULT NULL COMMENT 'Out-of-Network Co-Insurance',
  `CREATE_DATE` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATE_DATE` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`INS_ID`),
  KEY `CLIENT_ID` (`CLIENT_ID`),
  KEY `PATIENT_ID` (`PATIENT_ID`),
  CONSTRAINT `insurance_ibfk_1` FOREIGN KEY (`CLIENT_ID`) REFERENCES `CLIENT` (`CLIENT_ID`),
  CONSTRAINT `insurance_ibfk_2` FOREIGN KEY (`PATIENT_ID`) REFERENCES `PATIENT` (`PATIENT_ID`)
);

--https://fairhealthconsumer.org/images/Health_ID_Insurance_Card_Example.pdf

CREATE TABLE SMARTDROFFICE.STAFF(
  STAFF_ID BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL,
  EMAIL_ID VARCHAR(255) UNIQUE,
  NAME VARCHAR(255),
  FIRST_NAME VARCHAR(255),
  LAST_NAME VARCHAR(255),
  GENDER VARCHAR(1),
  PROFESSION VARCHAR(30) NOT NULL,
  ADDRESS_1 VARCHAR(30),
  ADDRESS_2 VARCHAR(30),
  CITY VARCHAR(30),
  STATE VARCHAR(30),
  CELL_PHONE VARCHAR(12),
  WORK_PHONE VARCHAR(12),
  CREATE_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UPDATE_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP  
);

CREATE TABLE SMARTDROFFICE.ROOM(
  ROOM_ID BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL,
  ROOM_TYPE VARCHAR(25),
  CREATE_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UPDATE_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP 
);

CREATE TABLE SMARTDROFFICE.APPOINTMENT(
  APPOINTMENT_ID BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL,
  CLIENT_ID BIGINT NOT NULL,
  PATIENT_ID BIGINT NOT NULL,
  ROOM_ID BIGINT NOT NULL,
  DR_ID BIGINT NOT NULL,
  NURSE_ID BIGINT NOT NULL,
  START_DTTM DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  END_DTTM DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,   
  CREATE_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UPDATE_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,  
  FOREIGN KEY (DR_ID) REFERENCES SMARTDROFFICE.STAFF (STAFF_ID),
  FOREIGN KEY (NURSE_ID) REFERENCES SMARTDROFFICE.STAFF (STAFF_ID) 
);

CREATE TABLE SMARTDROFFICE.SERVICE(
  SERVICE_ID BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL,
  CODE VARCHAR(30) NOT NULL,
  CATEGORY VARCHAR(20) NOT NULL,
  SUB_CATEGORY VARCHAR(20) NOT NULL,
  RATE DECIMAL(10,2) NOT NULL,
  SERVICE_DESC VARCHAR(100) NOT NULL,
  CREATE_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UPDATE_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE SMARTDROFFICE.PATIENT_SERVICE(
  PAT_SERVICE_ID BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL,
  CLIENT_ID BIGINT NOT NULL,
  PATIENT_ID BIGINT NOT NULL,
  ROOM_ID BIGINT NOT NULL,
  DR_ID BIGINT NOT NULL,
  NURSE_ID BIGINT NOT NULL,  
  SERVICE_DATE DATETIME NOT NULL,
  CREATE_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UPDATE_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,  
  FOREIGN KEY (CLIENT_ID) REFERENCES SMARTDROFFICE.CLIENT (CLIENT_ID),
  FOREIGN KEY (PATIENT_ID) REFERENCES SMARTDROFFICE.PATIENT (PATIENT_ID),
  FOREIGN KEY (DR_ID) REFERENCES SMARTDROFFICE.STAFF (STAFF_ID),
  FOREIGN KEY (NURSE_ID) REFERENCES SMARTDROFFICE.STAFF (STAFF_ID)
);

CREATE TABLE SMARTDROFFICE.PATIENT_SERVICE_DETAIL(
 PAT_SERVICE_DETAIL_ID BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL,
 PAT_SERVICE_ID BIGINT NOT NULL,
 SERVICE_ID BIGINT NOT NULL,
 QUANTITY BIGINT NOT NULL,
 UNIT_PRICE_AMT DECIMAL(10,2) NOT NULL,
 COPAY_AMT DECIMAL(10,2) NOT NULL,
 INSURANCE_REIM_AMT DECIMAL(10,2) NOT NULL,
 ADJUSTMENT_AMT  DECIMAL(10,2) NOT NULL,
 BALANCE_AMT  DECIMAL(10,2) NOT NULL,
 CREATE_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 UPDATE_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,  
 FOREIGN KEY (PAT_SERVICE_ID) REFERENCES SMARTDROFFICE.PATIENT_SERVICE (PAT_SERVICE_ID)
);


CREATE TABLE SMARTDROFFICE.CLIENT_BILLING(
  BILLING_ID BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL,
  CLIENT_ID BIGINT,
  CARD_TYPE VARCHAR(10),
  CARD_NUMBER VARCHAR(16),
  CVV VARCHAR(3),
  EXPIRY_MONTH VARCHAR(2),
  EXPIRY_YEAR VARCHAR(4),
  CREATE_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UPDATE_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, 
  FOREIGN KEY (CLIENT_ID) REFERENCES SMARTDROFFICE.CLIENT (CLIENT_ID) 
);

CREATE TABLE SMARTDROFFICE.CLIENT_SERVICE_BILLING(
 BILLING_ID BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL,
 CLIENT_ID BIGINT NOT NULL,
 PATIENT_ID BIGINT NOT NULL,
 BILLING_DATE DATETIME NOT NULL,
 PAYMENT_DURATION INT NOT NULL,
 CLIENT_BILLING_ID BIGINT,
 PAYMENT_DATE DATETIME, 
 PAID_AMT  DECIMAL(10,2) NOT NULL,
 BALANCE_AMT  DECIMAL(10,2) NOT NULL,
 CREATE_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 UPDATE_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, 
 FOREIGN KEY (CLIENT_ID) REFERENCES SMARTDROFFICE.CLIENT (CLIENT_ID),
 FOREIGN KEY (PATIENT_ID) REFERENCES SMARTDROFFICE.PATIENT (PATIENT_ID),
 FOREIGN KEY (CLIENT_BILLING_ID) REFERENCES SMARTDROFFICE.CLIENT_BILLING (BILLING_ID)
);

