REATE TABLE SMARTDROFFICE.CLIENT(
  CLIENT_ID BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL,
  EMAIL_ID VARCHAR(255) UNIQUE,
  NAME VARCHAR(255),
  FIRST_NAME VARCHAR(50),
  MIDDLE_NAME VARCHAR(50),
  LAST_NAME VARCHAR(50),
  GENDER VARCHAR(1),
  ADDRESS_1 VARCHAR(30),
  ADDRESS_2 VARCHAR(30),
  CITY VARCHAR(30),
  STATE VARCHAR(30),
  CELL VARCHAR(12),
  HOME_PHONE VARCHAR(12),
  CREATE_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UPDATE_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE SMARTDROFFICE.PATIENT(
  PATIENT_ID BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL,
  CLIENT_ID BIGINT NOT NULL,
  NAME VARCHAR(150),
  FIRST_NAME VARCHAR(50),
  MIDDLE_NAME VARCHAR(50),
  LAST_NAME VARCHAR(50),
  GENDER VARCHAR(1) NOT NULL,
  AGE INT NOT NULL,
  RELATION VARCHAR(20) NOT NULL,
  CREATE_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UPDATE_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (CLIENT_ID) REFERENCES SMARTDROFFICE.CLIENT (CLIENT_ID)
);

CREATE TABLE SMARTDROFFICE.INSURANCE(
  ID BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL,
  CLIENT_ID BIGINT,
  PATIENT_ID BIGINT,
  CREATE_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UPDATE_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,  
  FOREIGN KEY (CLIENT_ID) REFERENCES SMARTDROFFICE.CLIENT (CLIENT_ID),
  FOREIGN KEY (PATIENT_ID) REFERENCES SMARTDROFFICE.PATIENT (PATIENT_ID)
);

CREATE TABLE SMARTDROFFICE.STAFF(
  STAFF_ID BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL,
  EMAIL_ID VARCHAR(255) UNIQUE,
  NAME VARCHAR(255),
  FIRST_NAME VARCHAR(255),
  LAST_NAME VARCHAR(255),
  GENDER VARCHAR(1),
  PROFESSION VARCHAR(30) NOT NULL,
  ADDRESS_1 VARCHAR(30),
  ADDRESS_2 VARCHAR(30),
  CITY VARCHAR(30),
  STATE VARCHAR(30),
  CELL_PHONE VARCHAR(12),
  WORK_PHONE VARCHAR(12),
  CREATE_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UPDATE_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP  
);

CREATE TABLE SMARTDROFFICE.ROOM(
  ROOM_ID BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL,
  ROOM_TYPE VARCHAR(25),
  CREATE_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UPDATE_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP 
);

CREATE TABLE SMARTDROFFICE.APPOINTMENT(
  APPOINTMENT_ID BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL,
  CLIENT_ID BIGINT NOT NULL,
  PATIENT_ID BIGINT NOT NULL,
  ROOM_ID BIGINT NOT NULL,
  DR_ID BIGINT NOT NULL,
  NURSE_ID BIGINT NOT NULL,
  START_DTTM DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  END_DTTM DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,   
  CREATE_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UPDATE_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,  
  FOREIGN KEY (DR_ID) REFERENCES SMARTDROFFICE.STAFF (STAFF_ID),
  FOREIGN KEY (NURSE_ID) REFERENCES SMARTDROFFICE.STAFF (STAFF_ID) 
);

CREATE TABLE SMARTDROFFICE.SERVICE(
  SERVICE_ID BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL,
  SERVICE_CODE VARCHAR(30) NOT NULL,
  SERVICE_RATE DECIMAL(10,2) NOT NULL,
  SERVICE_DESC VARCHAR(100) NOT NULL,
  CREATE_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UPDATE_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE SMARTDROFFICE.PATIENT_SERVICE(
  PAT_SERVICE_ID BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL,
  CLIENT_ID BIGINT NOT NULL,
  PATIENT_ID BIGINT NOT NULL,
  ROOM_ID BIGINT NOT NULL,
  DR_ID BIGINT NOT NULL,
  NURSE_ID BIGINT NOT NULL,  
  CREATE_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UPDATE_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,  
  FOREIGN KEY (CLIENT_ID) REFERENCES SMARTDROFFICE.CLIENT (CLIENT_ID),
  FOREIGN KEY (PATIENT_ID) REFERENCES SMARTDROFFICE.PATIENT (PATIENT_ID),
  FOREIGN KEY (DR_ID) REFERENCES SMARTDROFFICE.STAFF (STAFF_ID),
  FOREIGN KEY (NURSE_ID) REFERENCES SMARTDROFFICE.STAFF (STAFF_ID)
);

CREATE TABLE SMARTDROFFICE.PATIENT_SERVICE_DETAIL(
 PAT_SERVICE_DETAIL_ID BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL,
 PAT_SERVICE_ID BIGINT NOT NULL,
 CREATE_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 UPDATE_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,  
 FOREIGN KEY (PAT_SERVICE_ID) REFERENCES SMARTDROFFICE.PATIENT_SERVICE (PAT_SERVICE_ID)
);


CREATE TABLE SMARTDROFFICE.CLIENT_BILLING(
  BILLING_ID BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL,
  CLIENT_ID BIGINT,
  CARD_TYPE VARCHAR(10),
  CARD_NUMBER VARCHAR(16),
  CVV VARCHAR(3),
  EXPIRY_MONTH VARCHAR(2),
  EXPIRY_YEAR VARCHAR(4),
  CREATE_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UPDATE_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, 
  FOREIGN KEY (CLIENT_ID) REFERENCES SMARTDROFFICE.CLIENT (CLIENT_ID) 
);

CREATE TABLE SMARTDROFFICE.PATIENT_SERVICE_BILLING(
 BILLING_ID BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL,
 CLIENT_ID BIGINT NOT NULL,
 PATIENT_ID BIGINT NOT NULL,
 BILLING_DATE DATETIME NOT NULL,
 PAYMENT_DURATION INT NOT NULL,
 CLIENT_BILLING_ID BIGINT,
 PAYMENT_DATE DATETIME, 
 CREATE_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 UPDATE_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, 
 FOREIGN KEY (CLIENT_ID) REFERENCES SMARTDROFFICE.CLIENT (CLIENT_ID),
 FOREIGN KEY (PATIENT_ID) REFERENCES SMARTDROFFICE.PATIENT (PATIENT_ID),
 FOREIGN KEY (CLIENT_BILLING_ID) REFERENCES SMARTDROFFICE.CLIENT_BILLING (BILLING_ID)
);

