spring:
  datasource:
    url: jdbc:mysql://localhost:3306/smartdroffice
    driver-class-name: com.mysql.jdbc.Driver
    initialize: true
    username: root
    password: password
    test-on-borrow: true
    test-while-idle: true
    validation-query: select 1;
    maxActive: 1
  jpa:
    show-sql: true
    generate-ddl: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        ddl-auto: validate